services:
  storage: # сервис с именем storage
    image: redis # использует образ redis:latest
    volumes:
      - ./data:/data # подключает диск
  counter: # сервис с именем counter
    image: surik95/counter
    environment:
      - REDIS_URL=redis://storage
      - PORT=3001
    depends_on:
      - storage
    command: ['npm', 'run', 'start']
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
    depends_on:
      - mongo
  liblary:
    image: surik95/library:latest
    working_dir: /app
    # build: ./ # собирает образ из папки ./counter
    # volumes:
    #  - ./:/app # подключает диск с кодом
    ports:
      - 80:3000 # мапит порт 80 хоста на порт контейнера
    environment:
      - URL_HOME=http://localhost:0080/
      - URL_COUNTER=http://counter:3001/
      - UrlDb=mongodb://root:example@mongo:27017
      - PORT=3000
    depends_on:
      - counter
      - mongo-express
    command: ['npm', 'run', 'start']
